name: Validate

on:
  push:
    branches:
      main
      
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        if: contains(github.event.head_commit.message, 'validate')
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Running Lint Command
        if: contains(github.event.head_commit.message, 'validate')
        run: |
          echo 'Linting code...'
          npm i @virtual-labs/buildexp@latest
          npx @virtual-labs/buildexp validate > lint.txt
          git add lint.txt
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Add new file with lint output"
          git push origin dev